# Generated by Django 6.1 on 2026-08-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showseat',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when seat entered LOCKED state. Used by Celery to release expired locks.', null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='showseat',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked'), ('BOOKED', 'Booked')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='api.movie'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
